# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7LTzjlWYcyhkYOsyGnPo4DYbKSTAX16
"""

scores = input().split()

numbers = []

for s in scores:
    numbers.append(int(s))

max_score = max(numbers)
min_score = min(numbers)
average = sum(numbers) / len(numbers)

print(max_score, min_score)
print(average)
