# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7LTzjlWYcyhkYOsyGnPo4DYbKSTAX16
"""

scores=input().split()
fail_count=0
for s in scores:
  if int(s)<60:
    fail_count+=1
print(fail_count)