# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7LTzjlWYcyhkYOsyGnPo4DYbKSTAX16
"""

scores = input().split()

numbers = []

for s in scores:
    numbers.append(int(s))

average = sum(numbers) / len(numbers)

print(average)
